config/routes.rb
Rails.application.routes.draw do
  root  'flights#index'
  get   'flights' => 'flights#index'

  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  
  # Associations
  has_many :departed_flights, class_name: Flight, foreign_key: :departure_airport_id
  has_many :arriving_flights, class_name: Flight, foreign_key: :destination_airport_id
end

app/models/booking.rb
class Booking < ActiveRecord::Base

  # Associations
  belongs_to :flight
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base

  # Associations
  belongs_to :from_airport, class_name: Airport, foreign_key: :departure_airport_id
  belongs_to :to_airport, class_name: Airport, foreign_key: :destination_airport_id

  has_many :bookings
  has_many :passenger_bookings, through: :bookings
  has_many :passengers, through: :bookings


  def self.search(from, to, date)
    where(departure_airport_id: from, destination_airport_id: to, date: Flight.format_date(date))
  end

  def self.format_date(date)
    date = date.to_date
    date.beginning_of_day..date.end_of_day
  end

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base

  # Associations
  has_many :passenger_bookings
  has_many :bookings, through: :passenger_bookings
  has_many :flights, through: :bookings

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
end

app/models/passenger_booking.rb
class PassengerBooking < ActiveRecord::Base

  # Associations
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_selected])
    @booking = Booking.new
    params[:passenger_count].to_i.times do
      @booking.passengers.build
    end
  end

  def create
    @booking = Booking.new(whitelist_params)
    respond_to do |format|
      if @booking.save
        @booking.passengers.each do |passenger|
          PassengerMailer.booking_info(passenger).deliver_now
        end
        flash.now[:success] = "Booking successful. You will be redirected to your booking info now."
        format.html {redirect_to root_url}
        format.js { }
      else
        format.js
      end

    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
  end

  private

  def whitelist_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight = Flight.new
    @airports = Airport.all.map { |airport| [airport.city, airport.id] }
    @dates = Flight.order("date asc").all.map { |flight| [flight.date.strftime("%d/%m/%Y")] }.uniq
    @passengers = [1, 2, 3, 4]


    if !params[:flight].nil?
      @from = params[:flight][:from_airport]
      @to = params[:flight][:to_airport]
      @date = params[:flight][:date]
      @passengers_select = params[:flight][:passengers]
      @flights = Flight.search(@from, @to, @date)

      respond_to do |format|
        format.html
        format.js
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.js.erb
<% if @booking.save %>

  $('#booking-form').hide();
  $('#success-notice').html("<%= j render 'shared/flash_messages' %>").hide().fadeIn();
  $('#errors_for_form').hide();

window.setTimeout(function() {
    window.location.href = "<%= booking_path(@booking) %>";
}, 5000);

<% else %>

  $('#errors_for_form').html("<%= j render 'shared/error_messages', object: @booking %>");

    $('html,body').animate({
        scrollTop: $("#errors_for_form").offset().top
});

<% end %>

app/views/bookings/new.html.erb
<div class="row" style="margin-top: -40px;">
  <div class="col-md-8 col-md-offset-2" id="search-form">
    <h1 class="text-center">Booking info</h1>
    <table class="table table-striped table-bordered">
      <thead>
      <tr>
        <th>Flight ID</th>
        <th>Date</th>
        <th>Time</th>
        <th>Passengers</th>
        <th>Departure</th>
        <th>Destination</th>
        <th>Price</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @flight.id %></td>
        <td><%= @flight.date.strftime("%d/%m/%Y") %></td>
        <td><%= @flight.date.strftime("%H:%m") %></td>
        <td><%= params[:passenger_count] %></td>
        <td><%= @flight.from_airport.code %></td>
        <td><%= @flight.to_airport.code %></td>
        <td><%= @flight.price %> &euro;</td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<% passenger_count = 1 %>
<br/>
<div id="success-notice" class="col-md-6 col-md-offset-3"></div>
<div id="errors_for_form" class="col-md-6 col-md-offset-3" style="padding-top: 20px;"></div>
<div class="row">

  <div class="col-md-6 col-md-offset-3" id="booking-form">
    <%= form_for @booking, remote: true do |booking| %><br/>


        <%= booking.fields_for :passengers do |passenger| %>

            <div class="row">
              <h5 class="text-center" style="font-size: 1.5em;">Passenger <%= passenger_count.to_s%></h5><br/>
              <div class="col-md-10 col-md-offset-1 well" style="margin-top:20px;">

                <% passenger_count += 1 %>
                <%= passenger.label :name %> <br/>
                <%= passenger.text_field :name, class: 'form-control' %><br/>

                <%= passenger.label :email %> <br/>
                <%= passenger.text_field :email, class: 'form-control' %><br/>
                <hr style="padding-bottom: 15px;"/>

              </div>
            </div>


        <% end %>
        <%= booking.hidden_field :flight_id, value: @flight.id %>


        <%= booking.submit "Confirm", class: 'form-control btn btn-primary', id: 'confirm-btn' %>

    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<% passengers_count = @booking.passengers.count %>


<div class="row" style="margin-top: -40px;">
  <div class="col-md-8 col-md-offset-2" id="search-form">
    <h1 class="text-center">Booking info</h1>
    <table class="table table-striped table-bordered">
      <thead>
      <tr>
        <th>Flight ID</th>
        <th>Date</th>
        <th>Time</th>
        <th>Passengers</th>
        <th>Departure</th>
        <th>Destination</th>
        <th>Price</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @flight.id %></td>
        <td><%= @flight.date.strftime("%d/%m/%Y") %></td>
        <td><%= @flight.date.strftime("%H:%m") %></td>
        <td><%= passengers_count %></td>
        <td><%= @flight.from_airport.code %></td>
        <td><%= @flight.to_airport.code %></td>
        <td><%= @flight.price %> &euro;</td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row" style="margin-top:40px;">
  <h1 class="text-center">Bookings for:</h1>

  <% @booking.passengers.each_with_index do |p, i| %>

      <div class="col-md-6 col-md-offset-3 well">
        <h5><strong>Name: </strong><%= p.name %></h5>
        <h5><strong>Email: </strong><%= p.email %></h5>
        <% if i == passengers_count-1 %>
            <code class="pull-right">Total: <%= passengers_count * @flight.price %> &euro;</code>
        <% end %>
      </div>

  <% end %>

</div>

<div class="row">
  <div class="col-md-3 col-md-offset-8">

  </div>
</div>

app/views/flights/_flight_form.html.erb
<% if !@flights.nil? %>
    <% if !@flights.empty? %>
        <%= form_tag new_booking_path, method: :get do %>
            <div class="row" id="flights-form">
              <div class="col-md-8 col-md-offset-2" style="margin-top:100px;">
                <table class="table table-striped table-bordered">
                  <thead>
                  <tr>
                    <th></th>
                    <th>Flight ID</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Passengers</th>
                    <th>Departure</th>
                    <th>Destination</th>
                    <th>Price</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @flights.each do |f| %>
                      <tr>
                        <td><%= radio_button_tag(:flight_selected, f.id, checked: f) %></td>
                        <td><%= f.id %></td>
                        <td><%= f.date.strftime("%d/%m/%Y") %></td>
                        <td><%= f.date.strftime("%H:%m") %></td>
                        <td><%= params[:flight][:passengers] %></td>
                        <td><%= f.from_airport.code %></td>
                        <td><%= f.to_airport.code %></td>
                        <td><%= f.price %> &euro;</td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
                <%= hidden_field_tag :passenger_count, params[:flight][:passengers] %>
                <%= submit_tag("Order", class: "form-control btn btn-primary btn-block search-btn", id: 'order-btn') %>
              </div>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/flights/index.html.erb
<div class="col-md-10 col-md-offset-1" id="search-form">
  <h1 class="text-center">Search for flights: </h1><br/>
  <%= form_for @flight, html: {method: :get}, remote: true do |f| %>
      <div class="row">
        <div class="col-md-4 col-md-offset-2 text-center">
          <%= f.label :from_airport %>
          <%= f.select(:from_airport, @airports, {selected: @from}, {:class => 'form-control', id: 'from_airport'}) %>
          <br/>
        </div>

        <div class="col-md-4 text-center">
          <%= f.label :to_airport %>
          <%= f.select(:to_airport, @airports, {selected: @to}, {:class => 'form-control', id: 'to_airport'}) %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 col-md-offset-2 text-center">
          <%= f.label :date %>
          <%= f.select(:date, @dates, {selected: @date}, {:class => 'form-control'}) %>
        </div>

        <div class="col-md-4 text-center">
          <%= f.label :passengers %>
          <%= f.select(:passengers, @passengers, {selected: @passengers_select}, {:class => 'form-control'}) %>
        </div>
      </div>
      <br/>
      <br/>

      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <%= f.submit "Search", id: 'search-btn', class: 'form-control btn btn-primary btn-block search-btn' %>
        </div>
      </div>
  <% end %>
</div>
<br/>

<div id="results" style="display: none;">

</div>

<script type="text/javascript">
    $('#search-btn').click(function () {
        $from = $('#from_airport option:selected').text();
        $to = $('#to_airport option:selected').text();
        if ($from == $to) {
            alert("Can't fly to the same city");
        }
    });
</script>

app/views/flights/index.js.erb
$('#results').html("<%= j (render 'flight_form') %>").fadeIn(600);

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default topnav" role="navigation">
  <div class="container topnav">
    <div class="navbar-header">
      <%= link_to root_url, id: 'logo', class: 'navbar-brand topnav' do %>
          <i class="fa fa-plane"></i>
          Flight Booker
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flight-Booker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container" id="wrap">
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        The form contains <%= pluralize(object.errors.count, "error") %>:
        <ul>
          <% object.errors.full_messages.each do |msg| %><br/>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
    <%= content_tag :div, class: "alert alert-#{type}" do %>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= msg %>
    <% end %>
<% end %>